name: UniVis
description: Interactive visualization for university performances.
version: 1.0.0
author: Davide <davideprimiceri95@hotmail.it>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  color: any

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.0
